name: Intraday Agent Scheduler

on:
  schedule:
    # Runs at 8:15 AM UTC (which is 8:45 AM IST)
    - cron: '15 3 * * 1-5'
  workflow_dispatch:

jobs:
  run-intraday-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "EMAIL_TO=${{ secrets.EMAIL_TO }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env

      - name: Run intraday agent
        run: python -m intraday.main
